name: CARE
favicon: null
layout_spectrum: 0.622844249708578
typography_spectrum: 0.64714
title: CARE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d1d1d'
    - '#585657'
    - '#f9a10b'
    - '#d1ae88'
    - '#f3d5bb'
  brandStrength: 0.07384785008616745
  lightness: 0.5496066382620484
  saturation: 0.4223269806243479
  rhythmicContrast: 0.5358252238947898
purpose: []
